name: "Deploy to Google Cloud Run"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: get repository name
          run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

        - name: Find and Replace
          uses: jacobtomlinson/gha-find-replace@v3
          with:
                find: "<REPOSITORY_NAME>"
                replace: ${{ env.REPOSITORY_NAME }}
                regex: false

        - id: 'auth'
          uses: 'google-github-actions/auth@v1'
          with:
            credentials_json: '${{ secrets.GOOGLE_CREDENTIALS_RAW }}'

        - name: Set up Google Cloud SDK
          uses: google-github-actions/setup-gcloud@v1.1.1

        - name: Configure docker for GCP
          run: gcloud auth configure-docker

        - name: Build and push Docker image
          uses: docker/build-push-action@v2
          with:
            context: .
            push: true
            tags: gcr.io/${{ vars.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}:latest
            build-args: |
              HTTP_PORT=80

        - name: Deploy to Cloud Run
          uses: google-github-actions/deploy-cloudrun@v1
          with:
            image: gcr.io/${{ vars.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}:latest
            service: ${{ env.REPOSITORY_NAME }}
            region: ${{ vars.REGION }}